type ThemeBaseColors = {
   [K in Theme]: {[X in BaseColors]: string};
 };

type ThemeColors = {
   [K in Theme]: {[X in ColorKeys]: string};
 };

export type Theme = 'General' | 'Neon_Style' | 'Neon_2_0';

type BaseColors = 
  'Basic_Primary_primary_50'
  | 'Basic_Primary_primary_100'
  | 'Basic_Primary_primary_200'
  | 'Basic_Primary_primary_300'
  | 'Basic_Primary_primary_400'
  | 'Basic_Primary_primary_500'
  | 'Basic_Primary_primary_600'
  | 'Basic_Primary_primary_700'
  | 'Basic_Primary_primary_800'
  | 'Basic_Primary_primary_900'
  | 'Basic_Dark_dark_50'
  | 'Basic_Dark_dark_100'
  | 'Basic_Dark_dark_200'
  | 'Basic_Dark_dark_300'
  | 'Basic_Dark_dark_400'
  | 'Basic_Dark_dark_500'
  | 'Basic_Dark_dark_600'
  | 'Basic_Dark_dark_700'
  | 'Basic_Dark_dark_800'
  | 'Basic_Dark_dark_900'
  | 'Basic_Secondary_secondary_50'
  | 'Basic_Secondary_secondary_100'
  | 'Basic_Secondary_secondary_200'
  | 'Basic_Secondary_secondary_300'
  | 'Basic_Secondary_secondary_400'
  | 'Basic_Secondary_secondary_500'
  | 'Basic_Secondary_secondary_600'
  | 'Basic_Secondary_secondary_700'
  | 'Basic_Secondary_secondary_800'
  | 'Basic_Secondary_secondary_900'
  | 'Basic_Info_info_50'
  | 'Basic_Info_info_100'
  | 'Basic_Info_info_200'
  | 'Basic_Info_info_300'
  | 'Basic_Info_info_400'
  | 'Basic_Info_info_500'
  | 'Basic_Info_info_600'
  | 'Basic_Info_info_700'
  | 'Basic_Info_info_800'
  | 'Basic_Info_info_900'
  | 'Basic_Danger_danger_50'
  | 'Basic_Danger_danger_100'
  | 'Basic_Danger_danger_200'
  | 'Basic_Danger_danger_300'
  | 'Basic_Danger_danger_400'
  | 'Basic_Danger_danger_500'
  | 'Basic_Danger_danger_600'
  | 'Basic_Danger_danger_700'
  | 'Basic_Danger_danger_800'
  | 'Basic_Danger_danger_900'
  | 'Basic_Warning_warning_50'
  | 'Basic_Warning_warning_100'
  | 'Basic_Warning_warning_200'
  | 'Basic_Warning_warning_300'
  | 'Basic_Warning_warning_400'
  | 'Basic_Warning_warning_500'
  | 'Basic_Warning_warning_600'
  | 'Basic_Warning_warning_700'
  | 'Basic_Warning_warning_800'
  | 'Basic_Warning_warning_900'
  | 'Basic_Success_success_50'
  | 'Basic_Success_success_100'
  | 'Basic_Success_success_200'
  | 'Basic_Success_success_300'
  | 'Basic_Success_success_400'
  | 'Basic_Success_success_500'
  | 'Basic_Success_success_600'
  | 'Basic_Success_success_700'
  | 'Basic_Success_success_800'
  | 'Basic_Success_success_900'
  | 'Basic_Light_light_50'
  | 'Basic_Light_light_100'
  | 'Basic_Light_light_200'
  | 'Basic_Light_light_300'
  | 'Basic_Light_light_400'
  | 'Basic_Light_light_500'
  | 'Basic_Light_light_600'
  | 'Basic_Light_light_700'
  | 'Basic_Light_light_800'
  | 'Basic_Light_light_900'
  | 'Basic_Neutral_Neutral_25'
  | 'Basic_Neutral_Neutral_100'
  | 'Basic_Neutral_Neutral_200'
  | 'Basic_Neutral_Neutral_300'
  | 'Basic_Neutral_Neutral_400'
  | 'Basic_Neutral_Neutral_150'
  | 'Basic_Neutral_Neutral_250'
  | 'Basic_Neutral_Neutral_350'
  | 'Basic_Neutral_Neutral_450'
  | 'Basic_Neutral_Neutral_500'
  | 'Basic_Neutral_Neutral_600'
  | 'Basic_Neutral_Neutral_550'
  | 'Basic_Neutral_Neutral_700'
  | 'Basic_Neutral_Neutral_800'
  | 'Basic_Neutral_Neutral_900'
  | 'Basic_Neutral_Neutral_50';

type ColorKeys = 
  BaseColors
  | 'Basic_Primary_primary_50'
  | 'Basic_Primary_primary_100'
  | 'Basic_Primary_primary_200'
  | 'Basic_Primary_primary_300'
  | 'Basic_Primary_primary_400'
  | 'Basic_Primary_primary_500'
  | 'Basic_Primary_primary_600'
  | 'Basic_Primary_primary_700'
  | 'Basic_Primary_primary_800'
  | 'Basic_Primary_primary_900'
  | 'Basic_Dark_dark_50'
  | 'Basic_Dark_dark_100'
  | 'Basic_Dark_dark_200'
  | 'Basic_Dark_dark_300'
  | 'Basic_Dark_dark_400'
  | 'Basic_Dark_dark_500'
  | 'Basic_Dark_dark_600'
  | 'Basic_Dark_dark_700'
  | 'Basic_Dark_dark_800'
  | 'Basic_Dark_dark_900'
  | 'Basic_Secondary_secondary_50'
  | 'Basic_Secondary_secondary_100'
  | 'Basic_Secondary_secondary_200'
  | 'Basic_Secondary_secondary_300'
  | 'Basic_Secondary_secondary_400'
  | 'Basic_Secondary_secondary_500'
  | 'Basic_Secondary_secondary_600'
  | 'Basic_Secondary_secondary_700'
  | 'Basic_Secondary_secondary_800'
  | 'Basic_Secondary_secondary_900'
  | 'Basic_Info_info_50'
  | 'Basic_Info_info_100'
  | 'Basic_Info_info_200'
  | 'Basic_Info_info_300'
  | 'Basic_Info_info_400'
  | 'Basic_Info_info_500'
  | 'Basic_Info_info_600'
  | 'Basic_Info_info_700'
  | 'Basic_Info_info_800'
  | 'Basic_Info_info_900'
  | 'Basic_Danger_danger_50'
  | 'Basic_Danger_danger_100'
  | 'Basic_Danger_danger_200'
  | 'Basic_Danger_danger_300'
  | 'Basic_Danger_danger_400'
  | 'Basic_Danger_danger_500'
  | 'Basic_Danger_danger_600'
  | 'Basic_Danger_danger_700'
  | 'Basic_Danger_danger_800'
  | 'Basic_Danger_danger_900'
  | 'Basic_Warning_warning_50'
  | 'Basic_Warning_warning_100'
  | 'Basic_Warning_warning_200'
  | 'Basic_Warning_warning_300'
  | 'Basic_Warning_warning_400'
  | 'Basic_Warning_warning_500'
  | 'Basic_Warning_warning_600'
  | 'Basic_Warning_warning_700'
  | 'Basic_Warning_warning_800'
  | 'Basic_Warning_warning_900'
  | 'Basic_Success_success_50'
  | 'Basic_Success_success_100'
  | 'Basic_Success_success_200'
  | 'Basic_Success_success_300'
  | 'Basic_Success_success_400'
  | 'Basic_Success_success_500'
  | 'Basic_Success_success_600'
  | 'Basic_Success_success_700'
  | 'Basic_Success_success_800'
  | 'Basic_Success_success_900'
  | 'Basic_Light_light_50'
  | 'Basic_Light_light_100'
  | 'Basic_Light_light_200'
  | 'Basic_Light_light_300'
  | 'Basic_Light_light_400'
  | 'Basic_Light_light_500'
  | 'Basic_Light_light_600'
  | 'Basic_Light_light_700'
  | 'Basic_Light_light_800'
  | 'Basic_Light_light_900'
  | 'Basic_Neutral_Neutral_25'
  | 'Basic_Neutral_Neutral_100'
  | 'Basic_Neutral_Neutral_200'
  | 'Basic_Neutral_Neutral_300'
  | 'Basic_Neutral_Neutral_400'
  | 'Basic_Neutral_Neutral_150'
  | 'Basic_Neutral_Neutral_250'
  | 'Basic_Neutral_Neutral_350'
  | 'Basic_Neutral_Neutral_450'
  | 'Basic_Neutral_Neutral_500'
  | 'Basic_Neutral_Neutral_600'
  | 'Basic_Neutral_Neutral_550'
  | 'Basic_Neutral_Neutral_700'
  | 'Basic_Neutral_Neutral_800'
  | 'Basic_Neutral_Neutral_900'
  | 'Basic_Neutral_Neutral_50'
  | 'Semantic_Button_button_primary_bg'
  | 'Semantic_Button_button_secondary_bg'
  | 'Semantic_Button_button_success_bg'
  | 'Semantic_Button_button_warning_bg'
  | 'Semantic_Button_button_danger_bg'
  | 'Semantic_Button_button_info_bg'
  | 'Semantic_Button_button_general_text'
  | 'Semantic_Button_button_other_text'
  | 'Semantic_Button_button_primary_hover'
  | 'Semantic_Button_button_secondary_hover'
  | 'Semantic_Button_button_success_hover'
  | 'Semantic_Button_button_warning_hover'
  | 'Semantic_Button_button_danger_hover'
  | 'Semantic_Button_button_disable_text'
  | 'Semantic_Button_button_disable_bg'
  | 'Semantic_Text_text_primary'
  | 'Semantic_Text_text_secondary'
  | 'Semantic_Text_text_success'
  | 'Semantic_Text_text_warning'
  | 'Semantic_Text_text_danger'
  | 'Semantic_Text_text_info'
  | 'Semantic_Text_text_disable_text'
  | 'Semantic_Text_text_heading_50'
  | 'Semantic_Text_text_body_50'
  | 'Semantic_Text_text_label'
  | 'Semantic_Text_text_placeholder'
  | 'Semantic_Text_text_body_100'
  | 'Semantic_Text_text_body_900'
  | 'Semantic_Text_text_body_800'
  | 'Semantic_Text_text_heading_900'
  | 'Semantic_Text_text_heading_100'
  | 'Semantic_Text_text_body_200'
  | 'Semantic_Border_border_primary'
  | 'Semantic_Border_border_secondary'
  | 'Semantic_Border_border_success'
  | 'Semantic_Border_border_warning'
  | 'Semantic_Border_border_danger'
  | 'Semantic_Border_border_info'
  | 'Semantic_Border_border_disable'
  | 'Semantic_Border_border_standard_100'
  | 'Semantic_Border_border_standard_50'
  | 'Semantic_Border_border_input'
  | 'Semantic_Border_border_standard_900'
  | 'Semantic_Icon_icon_primary'
  | 'Semantic_Icon_icon_attribute'
  | 'Semantic_Icon_icon_secondary'
  | 'Semantic_Icon_icon_black'
  | 'Semantic_Icon_icon_white'
  | 'Semantic_Icon_icon_disable'
  | 'Semantic_Icon_icon_nonactive'
  | 'Semantic_Other_checkbox_normal_border'
  | 'Semantic_Other_checkbox_disable_fill'
  | 'Semantic_Other_checkbox_disable_checked_fill'
  | 'Semantic_Other_checkbox_disable_checked_check'
  | 'Semantic_Other_checkbox_checked_fill'
  | 'Semantic_Other_checkbox_checked_check'
  | 'Semantic_Other_radio_normal_border'
  | 'Semantic_Other_radio_disable_border'
  | 'Semantic_Other_radio_disable_fill'
  | 'Semantic_Other_radio_checked_fill'
  | 'Semantic_Other_radio_checked_border'
  | 'Semantic_Other_switch_disable_fill'
  | 'Semantic_Other_switch_checked_fill'
  | 'Semantic_Other_checkbox_disable_border'
  | 'Semantic_General_general_fill_light'
  | 'Semantic_General_general_fill_light_2'
  | 'Semantic_General_general_fill_primary_2'
  | 'Semantic_General_general_fill_disable'
  | 'Semantic_General_general_fill_primary_1'
  | 'Semantic_General_general_fill_black_1'
  | 'Semantic_General_general_fill_black_2'
  | 'Semantic_General_general_fill_black_3'
  | 'Semantic_General_general_fill_black_4'
  | 'Semantic_Background_bg_black'
  | 'Semantic_Background_bg_black_2'
  | 'Semantic_Background_bg_primary'
  | 'Semantic_Background_bg_danger'
  | 'Semantic_Background_bg_warning'
  | 'Semantic_Background_bg_success'
  | 'Semantic_Background_bg_info'
  | 'Semantic_Background_bg_black_3'
  | 'Semantic_Background_bg_black_4'
  | 'Semantic_Background_bg_success_light'
  | 'Semantic_Background_bg_info_light'
  | 'Semantic_Background_bg_primary_light'
  | 'Semantic_Background_bg_danger_light'
  | 'Semantic_Background_bg_warning_light'
  | 'Semantic_Background_bg_secondary'
  | 'Semantic_Background_bg_soft'
  | 'Semantic_Background_bg_supersoft'
  | 'Semantic_Background_bg_disable';

const ThemeBaseColors: ThemeBaseColors = {
  General: {
    'Basic_Primary_primary_50': '#eef2ff',
    'Basic_Primary_primary_100': '#e0e7ff',
    'Basic_Primary_primary_200': '#c7d2fe',
    'Basic_Primary_primary_300': '#a5b4fc',
    'Basic_Primary_primary_400': '#818cf8',
    'Basic_Primary_primary_500': '#6366f1',
    'Basic_Primary_primary_600': '#4f46e5',
    'Basic_Primary_primary_700': '#4338ca',
    'Basic_Primary_primary_800': '#3730a3',
    'Basic_Primary_primary_900': '#312e81',
    'Basic_Dark_dark_50': '#e7e7eb',
    'Basic_Dark_dark_100': '#b6b5c1',
    'Basic_Dark_dark_200': '#9292a3',
    'Basic_Dark_dark_300': '#60607a',
    'Basic_Dark_dark_400': '#414160',
    'Basic_Dark_dark_500': '#121138',
    'Basic_Dark_dark_600': '#100f33',
    'Basic_Dark_dark_700': '#0d0c28',
    'Basic_Dark_dark_800': '#0a091f',
    'Basic_Dark_dark_900': '#080718',
    'Basic_Secondary_secondary_50': '#fff1f2',
    'Basic_Secondary_secondary_100': '#ffe4e6',
    'Basic_Secondary_secondary_200': '#fecdd3',
    'Basic_Secondary_secondary_300': '#fda4af',
    'Basic_Secondary_secondary_400': '#fb7185',
    'Basic_Secondary_secondary_500': '#f43f5e',
    'Basic_Secondary_secondary_600': '#e11d48',
    'Basic_Secondary_secondary_700': '#be123c',
    'Basic_Secondary_secondary_800': '#9f1239',
    'Basic_Secondary_secondary_900': '#881337',
    'Basic_Info_info_50': '#e9f6fe',
    'Basic_Info_info_100': '#e2f3fe',
    'Basic_Info_info_200': '#c5e5fe',
    'Basic_Info_info_300': '#a8d5fe',
    'Basic_Info_info_400': '#92c5fd',
    'Basic_Info_info_500': '#6facfc',
    'Basic_Info_info_600': '#5185d8',
    'Basic_Info_info_700': '#3763b5',
    'Basic_Info_info_800': '#234492',
    'Basic_Info_info_900': '#152e78',
    'Basic_Danger_danger_50': '#ffe6ef',
    'Basic_Danger_danger_100': '#ffc3c8',
    'Basic_Danger_danger_200': '#ffa7ae',
    'Basic_Danger_danger_300': '#ff7e89',
    'Basic_Danger_danger_400': '#ff6572',
    'Basic_Danger_danger_500': '#ff3f4f',
    'Basic_Danger_danger_600': '#e83948',
    'Basic_Danger_danger_700': '#b52d38',
    'Basic_Danger_danger_800': '#8c232b',
    'Basic_Danger_danger_900': '#6b1a21',
    'Basic_Warning_warning_50': '#fffbe6',
    'Basic_Warning_warning_100': '#fff3b1',
    'Basic_Warning_warning_200': '#ffee8b',
    'Basic_Warning_warning_300': '#ffe655',
    'Basic_Warning_warning_400': '#ffe135',
    'Basic_Warning_warning_500': '#ffd902',
    'Basic_Warning_warning_600': '#e8c502',
    'Basic_Warning_warning_700': '#b59a01',
    'Basic_Warning_warning_800': '#8c7701',
    'Basic_Warning_warning_900': '#6b5b01',
    'Basic_Success_success_50': '#ecf9ec',
    'Basic_Success_success_100': '#c3ecc3',
    'Basic_Success_success_200': '#a5e2a6',
    'Basic_Success_success_300': '#7cd57e',
    'Basic_Success_success_400': '#63cd65',
    'Basic_Success_success_500': '#3cc13e',
    'Basic_Success_success_600': '#37b038',
    'Basic_Success_success_700': '#2b892c',
    'Basic_Success_success_800': '#216a22',
    'Basic_Success_success_900': '#234e07',
    'Basic_Light_light_50': '#fcfcfd',
    'Basic_Light_light_100': '#f6f6f6',
    'Basic_Light_light_200': '#f3f3f4',
    'Basic_Light_light_300': '#eeeeee',
    'Basic_Light_light_400': '#eaeaeb',
    'Basic_Light_light_500': '#e5e5e6',
    'Basic_Light_light_600': '#d0d0d1',
    'Basic_Light_light_700': '#a3a3a3',
    'Basic_Light_light_800': '#7e7e7f',
    'Basic_Light_light_900': '#606061',
    'Basic_Neutral_Neutral_25': '#e7e7eb',
    'Basic_Neutral_Neutral_100': '#d1d0d2',
    'Basic_Neutral_Neutral_200': '#b6b5b9',
    'Basic_Neutral_Neutral_300': '#84808a',
    'Basic_Neutral_Neutral_400': '#4b4257',
    'Basic_Neutral_Neutral_150': '#cbcacd',
    'Basic_Neutral_Neutral_250': '#a09da4',
    'Basic_Neutral_Neutral_350': '#625b6b',
    'Basic_Neutral_Neutral_450': '#433b4e',
    'Basic_Neutral_Neutral_500': '#3d3647',
    'Basic_Neutral_Neutral_600': '#2f2a37',
    'Basic_Neutral_Neutral_550': '#352f3e',
    'Basic_Neutral_Neutral_700': '#27222d',
    'Basic_Neutral_Neutral_800': '#1f1b24',
    'Basic_Neutral_Neutral_900': '#18151c',
    'Basic_Neutral_Neutral_50': '#e7e7eb'
  },
  Neon_Style: {
    'Basic_Primary_primary_50': '#f7efff',
    'Basic_Primary_primary_100': '#e5ccfd',
    'Basic_Primary_primary_200': '#d8b4fd',
    'Basic_Primary_primary_300': '#c792fc',
    'Basic_Primary_primary_400': '#bc7dfb',
    'Basic_Primary_primary_500': '#ab5cfa',
    'Basic_Primary_primary_600': '#9c54e4',
    'Basic_Primary_primary_700': '#7941b2',
    'Basic_Primary_primary_800': '#5e338a',
    'Basic_Primary_primary_900': '#482769',
    'Basic_Dark_dark_50': '#ebebeb',
    'Basic_Dark_dark_100': '#bfbec0',
    'Basic_Dark_dark_200': '#a09ea2',
    'Basic_Dark_dark_300': '#747278',
    'Basic_Dark_dark_400': '#59565d',
    'Basic_Dark_dark_500': '#302c35',
    'Basic_Dark_dark_600': '#2c2830',
    'Basic_Dark_dark_700': '#221f26',
    'Basic_Dark_dark_800': '#1a181d',
    'Basic_Dark_dark_900': '#141216',
    'Basic_Secondary_secondary_50': '#fdf1e7',
    'Basic_Secondary_secondary_100': '#f9d4b5',
    'Basic_Secondary_secondary_200': '#f6bf91',
    'Basic_Secondary_secondary_300': '#f2a25f',
    'Basic_Secondary_secondary_400': '#f09040',
    'Basic_Secondary_secondary_500': '#ec8710',
    'Basic_Secondary_secondary_600': '#d76a0f',
    'Basic_Secondary_secondary_700': '#a8520b',
    'Basic_Secondary_secondary_800': '#824009',
    'Basic_Secondary_secondary_900': '#633107',
    'Basic_Info_info_50': '#ffefef',
    'Basic_Info_info_100': '#ffcecf',
    'Basic_Info_info_200': '#ffb7b7',
    'Basic_Info_info_300': '#fe9696',
    'Basic_Info_info_400': '#fe8182',
    'Basic_Info_info_500': '#fe6263',
    'Basic_Info_info_600': '#e7595a',
    'Basic_Info_info_700': '#b44646',
    'Basic_Info_info_800': '#8c3636',
    'Basic_Info_info_900': '#6b292a',
    'Basic_Danger_danger_50': '#ffe6ef',
    'Basic_Danger_danger_100': '#ffc3c8',
    'Basic_Danger_danger_200': '#ffa7ae',
    'Basic_Danger_danger_300': '#ff7e89',
    'Basic_Danger_danger_400': '#ff6572',
    'Basic_Danger_danger_500': '#ff3f4f',
    'Basic_Danger_danger_600': '#e83948',
    'Basic_Danger_danger_700': '#b52d38',
    'Basic_Danger_danger_800': '#8c232b',
    'Basic_Danger_danger_900': '#6b1a21',
    'Basic_Warning_warning_50': '#fffde7',
    'Basic_Warning_warning_100': '#fff9b5',
    'Basic_Warning_warning_200': '#fff692',
    'Basic_Warning_warning_300': '#fff260',
    'Basic_Warning_warning_400': '#ffef41',
    'Basic_Warning_warning_500': '#ffeb11',
    'Basic_Warning_warning_600': '#e8d60f',
    'Basic_Warning_warning_700': '#b5a70c',
    'Basic_Warning_warning_800': '#8c8109',
    'Basic_Warning_warning_900': '#6b6307',
    'Basic_Success_success_50': '#e6f8f1',
    'Basic_Success_success_100': '#b2e9d3',
    'Basic_Success_success_200': '#8cdfbe',
    'Basic_Success_success_300': '#58d0a0',
    'Basic_Success_success_400': '#38c78d',
    'Basic_Success_success_500': '#06b971',
    'Basic_Success_success_600': '#05a867',
    'Basic_Success_success_700': '#048350',
    'Basic_Success_success_800': '#03663e',
    'Basic_Success_success_900': '#034e2f',
    'Basic_Light_light_50': '#fdfdfd',
    'Basic_Light_light_100': '#f6f6f6',
    'Basic_Light_light_200': '#f4f4f4',
    'Basic_Light_light_300': '#eeeeee',
    'Basic_Light_light_400': '#ebebeb',
    'Basic_Light_light_500': '#e6e6e6',
    'Basic_Light_light_600': '#d0d0d1',
    'Basic_Light_light_700': '#a3a3a3',
    'Basic_Light_light_800': '#7e7e7f',
    'Basic_Light_light_900': '#606061',
    'Basic_Neutral_Neutral_25': '#f5f5f5',
    'Basic_Neutral_Neutral_100': '#d6d5d8',
    'Basic_Neutral_Neutral_200': '#b6b5b9',
    'Basic_Neutral_Neutral_300': '#84808a',
    'Basic_Neutral_Neutral_400': '#4b4257',
    'Basic_Neutral_Neutral_150': '#cbcacd',
    'Basic_Neutral_Neutral_250': '#a09da4',
    'Basic_Neutral_Neutral_350': '#625b6b',
    'Basic_Neutral_Neutral_450': '#433b4e',
    'Basic_Neutral_Neutral_500': '#3d3647',
    'Basic_Neutral_Neutral_600': '#2f2a37',
    'Basic_Neutral_Neutral_550': '#352f3e',
    'Basic_Neutral_Neutral_700': '#27222d',
    'Basic_Neutral_Neutral_800': '#1f1b24',
    'Basic_Neutral_Neutral_900': '#18151c',
    'Basic_Neutral_Neutral_50': '#efefef'
  },
  Neon_2_0: {
    'Basic_Primary_primary_50': '#f1e8fe',
    'Basic_Primary_primary_100': '#e1cefd',
    'Basic_Primary_primary_200': '#d1b0fc',
    'Basic_Primary_primary_300': '#bf8dfb',
    'Basic_Primary_primary_400': '#ab5cfa',
    'Basic_Primary_primary_500': '#9952e0',
    'Basic_Primary_primary_600': '#8447c2',
    'Basic_Primary_primary_700': '#6c3a9e',
    'Basic_Primary_primary_800': '#4c2970',
    'Basic_Primary_primary_900': '#361d4f',
    'Basic_Dark_dark_50': '#efefef',
    'Basic_Dark_dark_100': '#ddeedd',
    'Basic_Dark_dark_200': '#cbcacd',
    'Basic_Dark_dark_300': '#b6b5b9',
    'Basic_Dark_dark_400': '#a09da4',
    'Basic_Dark_dark_500': '#84808a',
    'Basic_Dark_dark_600': '#625b6b',
    'Basic_Dark_dark_700': '#4b4257',
    'Basic_Dark_dark_800': '#1a181d',
    'Basic_Dark_dark_900': '#141216',
    'Basic_Secondary_secondary_50': '#fdf1e7',
    'Basic_Secondary_secondary_100': '#f9d4b5',
    'Basic_Secondary_secondary_200': '#f6bf91',
    'Basic_Secondary_secondary_300': '#f2a25f',
    'Basic_Secondary_secondary_400': '#f09040',
    'Basic_Secondary_secondary_500': '#ec8710',
    'Basic_Secondary_secondary_600': '#d76a0f',
    'Basic_Secondary_secondary_700': '#a8520b',
    'Basic_Secondary_secondary_800': '#824009',
    'Basic_Secondary_secondary_900': '#633107',
    'Basic_Info_info_50': '#ffefef',
    'Basic_Info_info_100': '#ffcecf',
    'Basic_Info_info_200': '#ffb7b7',
    'Basic_Info_info_300': '#fe9696',
    'Basic_Info_info_400': '#fe8182',
    'Basic_Info_info_500': '#fe6263',
    'Basic_Info_info_600': '#e7595a',
    'Basic_Info_info_700': '#b44646',
    'Basic_Info_info_800': '#8c3636',
    'Basic_Info_info_900': '#6b292a',
    'Basic_Danger_danger_50': '#ffe6ef',
    'Basic_Danger_danger_100': '#ffc3c8',
    'Basic_Danger_danger_200': '#ffa7ae',
    'Basic_Danger_danger_300': '#ff7e89',
    'Basic_Danger_danger_400': '#ff6572',
    'Basic_Danger_danger_500': '#ff3f4f',
    'Basic_Danger_danger_600': '#e83948',
    'Basic_Danger_danger_700': '#b52d38',
    'Basic_Danger_danger_800': '#8c232b',
    'Basic_Danger_danger_900': '#6b1a21',
    'Basic_Warning_warning_50': '#fffde7',
    'Basic_Warning_warning_100': '#fff9b5',
    'Basic_Warning_warning_200': '#fff692',
    'Basic_Warning_warning_300': '#fff260',
    'Basic_Warning_warning_400': '#ffef41',
    'Basic_Warning_warning_500': '#ffeb11',
    'Basic_Warning_warning_600': '#e8d60f',
    'Basic_Warning_warning_700': '#b5a70c',
    'Basic_Warning_warning_800': '#8c8109',
    'Basic_Warning_warning_900': '#6b6307',
    'Basic_Success_success_50': '#e6f8f1',
    'Basic_Success_success_100': '#b2e9d3',
    'Basic_Success_success_200': '#8cdfbe',
    'Basic_Success_success_300': '#58d0a0',
    'Basic_Success_success_400': '#38c78d',
    'Basic_Success_success_500': '#06b971',
    'Basic_Success_success_600': '#05a867',
    'Basic_Success_success_700': '#048350',
    'Basic_Success_success_800': '#03663e',
    'Basic_Success_success_900': '#034e2f',
    'Basic_Light_light_50': '#fdfdfd',
    'Basic_Light_light_100': '#f6f6f6',
    'Basic_Light_light_200': '#f4f4f4',
    'Basic_Light_light_300': '#eeeeee',
    'Basic_Light_light_400': '#ebebeb',
    'Basic_Light_light_500': '#e6e6e6',
    'Basic_Light_light_600': '#d0d0d1',
    'Basic_Light_light_700': '#a3a3a3',
    'Basic_Light_light_800': '#7e7e7f',
    'Basic_Light_light_900': '#606061',
    'Basic_Neutral_Neutral_25': '#f5f5f5',
    'Basic_Neutral_Neutral_100': '#e0dfe1',
    'Basic_Neutral_Neutral_200': '#b6b5b9',
    'Basic_Neutral_Neutral_300': '#84808a',
    'Basic_Neutral_Neutral_400': '#4b4257',
    'Basic_Neutral_Neutral_150': '#cbcacd',
    'Basic_Neutral_Neutral_250': '#a09da4',
    'Basic_Neutral_Neutral_350': '#625b6b',
    'Basic_Neutral_Neutral_450': '#433b4e',
    'Basic_Neutral_Neutral_500': '#3d3647',
    'Basic_Neutral_Neutral_600': '#2f2a37',
    'Basic_Neutral_Neutral_550': '#352f3e',
    'Basic_Neutral_Neutral_700': '#27222d',
    'Basic_Neutral_Neutral_800': '#1f1b24',
    'Basic_Neutral_Neutral_900': '#18151c',
    'Basic_Neutral_Neutral_50': '#efefef'
  },
};

const Colors: ThemeColors = {
  General: {
    'Semantic_Button_button_primary_bg': 'Basic_Primary_primary_500',
    'Semantic_Button_button_secondary_bg': 'Basic_Secondary_secondary_500',
    'Semantic_Button_button_success_bg': 'Basic_Success_success_500',
    'Semantic_Button_button_warning_bg': 'Basic_Warning_warning_500',
    'Semantic_Button_button_danger_bg': 'Basic_Danger_danger_500',
    'Semantic_Button_button_info_bg': 'Basic_Info_info_500',
    'Semantic_Button_button_general_text': 'Basic_Light_light_50',
    'Semantic_Button_button_other_text': 'Basic_Dark_dark_900',
    'Semantic_Button_button_primary_hover': 'Basic_Primary_primary_600',
    'Semantic_Button_button_secondary_hover': 'Basic_Secondary_secondary_600',
    'Semantic_Button_button_success_hover': 'Basic_Success_success_600',
    'Semantic_Button_button_warning_hover': 'Basic_Warning_warning_600',
    'Semantic_Button_button_danger_hover': 'Basic_Danger_danger_600',
    'Semantic_Button_button_disable_text': 'Basic_Light_light_600',
    'Semantic_Button_button_disable_bg': 'Basic_Light_light_400',
    'Semantic_Text_text_primary': 'Basic_Primary_primary_500',
    'Semantic_Text_text_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Text_text_success': 'Basic_Success_success_500',
    'Semantic_Text_text_warning': 'Basic_Warning_warning_500',
    'Semantic_Text_text_danger': 'Basic_Danger_danger_500',
    'Semantic_Text_text_info': 'Basic_Info_info_500',
    'Semantic_Text_text_disable_text': 'Basic_Light_light_600',
    'Semantic_Text_text_heading_50': 'Basic_Dark_dark_900',
    'Semantic_Text_text_body_50': 'Basic_Dark_dark_500',
    'Semantic_Text_text_label': 'Basic_Dark_dark_900',
    'Semantic_Text_text_placeholder': 'Basic_Dark_dark_100',
    'Semantic_Text_text_body_100': 'Basic_Dark_dark_900',
    'Semantic_Text_text_body_900': 'Basic_Dark_dark_900',
    'Semantic_Text_text_body_800': 'Basic_Dark_dark_500',
    'Semantic_Text_text_heading_900': 'Basic_Dark_dark_900',
    'Semantic_Text_text_heading_100': 'Basic_Dark_dark_900',
    'Semantic_Text_text_body_200': 'Basic_Dark_dark_900',
    'Semantic_Border_border_primary': 'Basic_Primary_primary_600',
    'Semantic_Border_border_secondary': 'Basic_Secondary_secondary_600',
    'Semantic_Border_border_success': 'Basic_Success_success_600',
    'Semantic_Border_border_warning': 'Basic_Warning_warning_600',
    'Semantic_Border_border_danger': 'Basic_Danger_danger_600',
    'Semantic_Border_border_info': 'Basic_Info_info_600',
    'Semantic_Border_border_disable': 'Basic_Light_light_700',
    'Semantic_Border_border_standard_100': 'Basic_Light_light_600',
    'Semantic_Border_border_standard_50': 'Basic_Light_light_300',
    'Semantic_Border_border_input': 'Basic_Light_light_300',
    'Semantic_Border_border_standard_900': 'Basic_Light_light_600',
    'Semantic_Icon_icon_primary': 'Basic_Primary_primary_500',
    'Semantic_Icon_icon_attribute': 'Basic_Dark_dark_300',
    'Semantic_Icon_icon_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Icon_icon_black': 'Basic_Dark_dark_900',
    'Semantic_Icon_icon_white': 'Basic_Light_light_50',
    'Semantic_Icon_icon_disable': 'Basic_Dark_dark_900',
    'Semantic_Icon_icon_nonactive': 'Basic_Dark_dark_900',
    'Semantic_Other_checkbox_normal_border': 'Basic_Dark_dark_100',
    'Semantic_Other_checkbox_disable_fill': 'Basic_Light_light_400',
    'Semantic_Other_checkbox_disable_checked_fill': 'Basic_Light_light_400',
    'Semantic_Other_checkbox_disable_checked_check': 'Basic_Dark_dark_100',
    'Semantic_Other_checkbox_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_checkbox_checked_check': 'Basic_Light_light_50',
    'Semantic_Other_radio_normal_border': 'Basic_Dark_dark_100',
    'Semantic_Other_radio_disable_border': 'Basic_Dark_dark_100',
    'Semantic_Other_radio_disable_fill': 'Basic_Dark_dark_100',
    'Semantic_Other_radio_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_radio_checked_border': 'Basic_Primary_primary_500',
    'Semantic_Other_switch_disable_fill': 'Basic_Dark_dark_100',
    'Semantic_Other_switch_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_checkbox_disable_border': 'Basic_Dark_dark_100',
    'Semantic_General_general_fill_light': 'Basic_Light_light_50',
    'Semantic_General_general_fill_light_2': 'Basic_Light_light_100',
    'Semantic_General_general_fill_primary_2': 'Basic_Primary_primary_500',
    'Semantic_General_general_fill_disable': 'Basic_Dark_dark_100',
    'Semantic_General_general_fill_primary_1': 'Basic_Primary_primary_50',
    'Semantic_General_general_fill_black_1': 'Basic_Dark_dark_900',
    'Semantic_General_general_fill_black_2': 'Basic_Dark_dark_800',
    'Semantic_General_general_fill_black_3': 'Basic_Dark_dark_700',
    'Semantic_General_general_fill_black_4': 'Basic_Dark_dark_600',
    'Semantic_Background_bg_black': 'Basic_Dark_dark_800',
    'Semantic_Background_bg_black_2': 'Basic_Dark_dark_800',
    'Semantic_Background_bg_primary': 'Basic_Primary_primary_600',
    'Semantic_Background_bg_danger': 'Basic_Danger_danger_600',
    'Semantic_Background_bg_warning': 'Basic_Warning_warning_600',
    'Semantic_Background_bg_success': 'Basic_Success_success_600',
    'Semantic_Background_bg_info': 'Basic_Info_info_600',
    'Semantic_Background_bg_black_3': 'Basic_Dark_dark_700',
    'Semantic_Background_bg_black_4': 'Basic_Dark_dark_600',
    'Semantic_Background_bg_success_light': 'Basic_Success_success_50',
    'Semantic_Background_bg_info_light': 'Basic_Info_info_50',
    'Semantic_Background_bg_primary_light': 'Basic_Primary_primary_50',
    'Semantic_Background_bg_danger_light': 'Basic_Danger_danger_50',
    'Semantic_Background_bg_warning_light': 'Basic_Warning_warning_50',
    'Semantic_Background_bg_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Background_bg_soft': '#ffffff',
    'Semantic_Background_bg_supersoft': '#ffffff',
    'Semantic_Background_bg_disable': '#ffffff',
    ...ThemeBaseColors.General,
  },
  Neon_Style: {
    'Semantic_Button_button_primary_bg': 'Basic_Primary_primary_500',
    'Semantic_Button_button_secondary_bg': 'Basic_Secondary_secondary_500',
    'Semantic_Button_button_success_bg': 'Basic_Success_success_500',
    'Semantic_Button_button_warning_bg': 'Basic_Warning_warning_500',
    'Semantic_Button_button_danger_bg': 'Basic_Danger_danger_500',
    'Semantic_Button_button_info_bg': 'Basic_Info_info_500',
    'Semantic_Button_button_general_text': 'Basic_Light_light_50',
    'Semantic_Button_button_other_text': 'Basic_Dark_dark_900',
    'Semantic_Button_button_primary_hover': 'Basic_Primary_primary_600',
    'Semantic_Button_button_secondary_hover': 'Basic_Secondary_secondary_600',
    'Semantic_Button_button_success_hover': 'Basic_Success_success_600',
    'Semantic_Button_button_warning_hover': 'Basic_Warning_warning_600',
    'Semantic_Button_button_danger_hover': 'Basic_Danger_danger_600',
    'Semantic_Button_button_disable_text': 'Basic_Light_light_600',
    'Semantic_Button_button_disable_bg': 'Basic_Light_light_400',
    'Semantic_Text_text_primary': 'Basic_Primary_primary_500',
    'Semantic_Text_text_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Text_text_success': 'Basic_Success_success_500',
    'Semantic_Text_text_warning': 'Basic_Warning_warning_500',
    'Semantic_Text_text_danger': 'Basic_Danger_danger_500',
    'Semantic_Text_text_info': 'Basic_Info_info_500',
    'Semantic_Text_text_disable_text': 'Basic_Light_light_600',
    'Semantic_Text_text_heading_50': 'Basic_Light_light_50',
    'Semantic_Text_text_body_50': 'Basic_Light_light_100',
    'Semantic_Text_text_label': 'Basic_Light_light_50',
    'Semantic_Text_text_placeholder': 'Basic_Dark_dark_400',
    'Semantic_Text_text_body_100': 'Basic_Light_light_400',
    'Semantic_Text_text_body_900': 'Basic_Dark_dark_800',
    'Semantic_Text_text_body_800': 'Basic_Dark_dark_500',
    'Semantic_Text_text_heading_900': 'Basic_Dark_dark_800',
    'Semantic_Text_text_heading_100': 'Basic_Light_light_600',
    'Semantic_Text_text_body_200': 'Basic_Light_light_600',
    'Semantic_Border_border_primary': 'Basic_Primary_primary_600',
    'Semantic_Border_border_secondary': 'Basic_Secondary_secondary_600',
    'Semantic_Border_border_success': 'Basic_Success_success_600',
    'Semantic_Border_border_warning': 'Basic_Warning_warning_600',
    'Semantic_Border_border_danger': 'Basic_Danger_danger_600',
    'Semantic_Border_border_info': 'Basic_Info_info_600',
    'Semantic_Border_border_disable': 'Basic_Light_light_700',
    'Semantic_Border_border_standard_100': 'Basic_Neutral_Neutral_450',
    'Semantic_Border_border_standard_50': 'Basic_Neutral_Neutral_400',
    'Semantic_Border_border_input': 'Basic_Dark_dark_700',
    'Semantic_Border_border_standard_900': 'Basic_Neutral_Neutral_300',
    'Semantic_Icon_icon_primary': 'Basic_Primary_primary_500',
    'Semantic_Icon_icon_attribute': 'Basic_Dark_dark_300',
    'Semantic_Icon_icon_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Icon_icon_black': 'Basic_Dark_dark_900',
    'Semantic_Icon_icon_white': 'Basic_Light_light_50',
    'Semantic_Icon_icon_disable': 'Basic_Dark_dark_900',
    'Semantic_Icon_icon_nonactive': 'Basic_Neutral_Neutral_300',
    'Semantic_Other_checkbox_normal_border': 'Basic_Dark_dark_100',
    'Semantic_Other_checkbox_disable_fill': 'Basic_Light_light_400',
    'Semantic_Other_checkbox_disable_checked_fill': 'Basic_Light_light_400',
    'Semantic_Other_checkbox_disable_checked_check': 'Basic_Dark_dark_100',
    'Semantic_Other_checkbox_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_checkbox_checked_check': 'Basic_Light_light_50',
    'Semantic_Other_radio_normal_border': 'Basic_Dark_dark_100',
    'Semantic_Other_radio_disable_border': 'Basic_Dark_dark_100',
    'Semantic_Other_radio_disable_fill': 'Basic_Dark_dark_100',
    'Semantic_Other_radio_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_radio_checked_border': 'Basic_Primary_primary_500',
    'Semantic_Other_switch_disable_fill': 'Basic_Dark_dark_100',
    'Semantic_Other_switch_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_checkbox_disable_border': 'Basic_Dark_dark_100',
    'Semantic_General_general_fill_light': 'Basic_Light_light_50',
    'Semantic_General_general_fill_light_2': 'Basic_Light_light_100',
    'Semantic_General_general_fill_primary_2': 'Basic_Primary_primary_500',
    'Semantic_General_general_fill_disable': 'Basic_Dark_dark_100',
    'Semantic_General_general_fill_primary_1': 'Basic_Primary_primary_50',
    'Semantic_General_general_fill_black_1': 'Basic_Dark_dark_900',
    'Semantic_General_general_fill_black_2': 'Basic_Dark_dark_800',
    'Semantic_General_general_fill_black_3': 'Basic_Dark_dark_700',
    'Semantic_General_general_fill_black_4': 'Basic_Dark_dark_600',
    'Semantic_Background_bg_black': 'Basic_Dark_dark_900',
    'Semantic_Background_bg_black_2': 'Basic_Dark_dark_800',
    'Semantic_Background_bg_primary': 'Basic_Primary_primary_600',
    'Semantic_Background_bg_danger': 'Basic_Danger_danger_600',
    'Semantic_Background_bg_warning': 'Basic_Warning_warning_600',
    'Semantic_Background_bg_success': 'Basic_Success_success_600',
    'Semantic_Background_bg_info': 'Basic_Info_info_600',
    'Semantic_Background_bg_black_3': 'Basic_Dark_dark_700',
    'Semantic_Background_bg_black_4': 'Basic_Dark_dark_600',
    'Semantic_Background_bg_success_light': 'Basic_Success_success_50',
    'Semantic_Background_bg_info_light': 'Basic_Info_info_50',
    'Semantic_Background_bg_primary_light': 'Basic_Primary_primary_50',
    'Semantic_Background_bg_danger_light': 'Basic_Danger_danger_50',
    'Semantic_Background_bg_warning_light': 'Basic_Warning_warning_50',
    'Semantic_Background_bg_secondary': 'Basic_Secondary_secondary_600',
    'Semantic_Background_bg_soft': '#ffffff',
    'Semantic_Background_bg_supersoft': '#ffffff',
    'Semantic_Background_bg_disable': 'Basic_Neutral_Neutral_350',
    ...ThemeBaseColors.Neon_Style,
  },
  Neon_2_0: {
    'Semantic_Button_button_primary_bg': 'Basic_Primary_primary_500',
    'Semantic_Button_button_secondary_bg': 'Basic_Secondary_secondary_500',
    'Semantic_Button_button_success_bg': 'Basic_Success_success_500',
    'Semantic_Button_button_warning_bg': 'Basic_Warning_warning_500',
    'Semantic_Button_button_danger_bg': 'Basic_Danger_danger_500',
    'Semantic_Button_button_info_bg': 'Basic_Info_info_500',
    'Semantic_Button_button_general_text': 'Basic_Light_light_50',
    'Semantic_Button_button_other_text': 'Basic_Dark_dark_900',
    'Semantic_Button_button_primary_hover': 'Basic_Primary_primary_600',
    'Semantic_Button_button_secondary_hover': 'Basic_Secondary_secondary_600',
    'Semantic_Button_button_success_hover': 'Basic_Success_success_600',
    'Semantic_Button_button_warning_hover': 'Basic_Warning_warning_600',
    'Semantic_Button_button_danger_hover': 'Basic_Danger_danger_600',
    'Semantic_Button_button_disable_text': 'Basic_Light_light_600',
    'Semantic_Button_button_disable_bg': 'Basic_Light_light_400',
    'Semantic_Text_text_primary': 'Basic_Primary_primary_500',
    'Semantic_Text_text_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Text_text_success': 'Basic_Success_success_500',
    'Semantic_Text_text_warning': 'Basic_Warning_warning_500',
    'Semantic_Text_text_danger': 'Basic_Danger_danger_500',
    'Semantic_Text_text_info': 'Basic_Info_info_500',
    'Semantic_Text_text_disable_text': 'Basic_Neutral_Neutral_300',
    'Semantic_Text_text_heading_50': 'Basic_Neutral_Neutral_25',
    'Semantic_Text_text_body_50': 'Basic_Neutral_Neutral_50',
    'Semantic_Text_text_label': 'Basic_Light_light_50',
    'Semantic_Text_text_placeholder': 'Basic_Neutral_Neutral_300',
    'Semantic_Text_text_body_100': 'Basic_Neutral_Neutral_150',
    'Semantic_Text_text_body_900': 'Basic_Dark_dark_800',
    'Semantic_Text_text_body_800': 'Basic_Dark_dark_500',
    'Semantic_Text_text_heading_900': 'Basic_Dark_dark_800',
    'Semantic_Text_text_heading_100': 'Basic_Light_light_600',
    'Semantic_Text_text_body_200': 'Basic_Neutral_Neutral_200',
    'Semantic_Border_border_primary': 'Basic_Primary_primary_600',
    'Semantic_Border_border_secondary': 'Basic_Secondary_secondary_600',
    'Semantic_Border_border_success': 'Basic_Success_success_600',
    'Semantic_Border_border_warning': 'Basic_Warning_warning_600',
    'Semantic_Border_border_danger': 'Basic_Danger_danger_600',
    'Semantic_Border_border_info': 'Basic_Info_info_600',
    'Semantic_Border_border_disable': 'Basic_Neutral_Neutral_600',
    'Semantic_Border_border_standard_100': 'Basic_Neutral_Neutral_450',
    'Semantic_Border_border_standard_50': 'Basic_Neutral_Neutral_400',
    'Semantic_Border_border_input': 'Basic_Dark_dark_700',
    'Semantic_Border_border_standard_900': 'Basic_Neutral_Neutral_300',
    'Semantic_Icon_icon_primary': 'Basic_Primary_primary_500',
    'Semantic_Icon_icon_attribute': 'Basic_Neutral_Neutral_400',
    'Semantic_Icon_icon_secondary': 'Basic_Secondary_secondary_500',
    'Semantic_Icon_icon_black': 'Basic_Neutral_Neutral_800',
    'Semantic_Icon_icon_white': 'Basic_Neutral_Neutral_25',
    'Semantic_Icon_icon_disable': 'Basic_Neutral_Neutral_300',
    'Semantic_Icon_icon_nonactive': 'Basic_Neutral_Neutral_300',
    'Semantic_Other_checkbox_normal_border': 'Basic_Neutral_Neutral_400',
    'Semantic_Other_checkbox_disable_fill': 'Basic_Light_light_400',
    'Semantic_Other_checkbox_disable_checked_fill': 'Basic_Light_light_400',
    'Semantic_Other_checkbox_disable_checked_check': 'Basic_Neutral_Neutral_400',
    'Semantic_Other_checkbox_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_checkbox_checked_check': 'Basic_Neutral_Neutral_25',
    'Semantic_Other_radio_normal_border': 'Basic_Neutral_Neutral_400',
    'Semantic_Other_radio_disable_border': 'Basic_Neutral_Neutral_400',
    'Semantic_Other_radio_disable_fill': 'Basic_Neutral_Neutral_400',
    'Semantic_Other_radio_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_radio_checked_border': 'Basic_Primary_primary_500',
    'Semantic_Other_switch_disable_fill': 'Basic_Neutral_Neutral_400',
    'Semantic_Other_switch_checked_fill': 'Basic_Primary_primary_500',
    'Semantic_Other_checkbox_disable_border': 'Basic_Neutral_Neutral_400',
    'Semantic_General_general_fill_light': 'Basic_Light_light_50',
    'Semantic_General_general_fill_light_2': 'Basic_Light_light_100',
    'Semantic_General_general_fill_primary_2': 'Basic_Primary_primary_500',
    'Semantic_General_general_fill_disable': 'Basic_Dark_dark_100',
    'Semantic_General_general_fill_primary_1': 'Basic_Primary_primary_50',
    'Semantic_General_general_fill_black_1': 'Basic_Dark_dark_900',
    'Semantic_General_general_fill_black_2': 'Basic_Dark_dark_800',
    'Semantic_General_general_fill_black_3': 'Basic_Dark_dark_700',
    'Semantic_General_general_fill_black_4': 'Basic_Dark_dark_600',
    'Semantic_Background_bg_black': 'Basic_Neutral_Neutral_900',
    'Semantic_Background_bg_black_2': 'Basic_Neutral_Neutral_700',
    'Semantic_Background_bg_primary': 'Basic_Primary_primary_600',
    'Semantic_Background_bg_danger': 'Basic_Danger_danger_600',
    'Semantic_Background_bg_warning': 'Basic_Warning_warning_600',
    'Semantic_Background_bg_success': 'Basic_Success_success_600',
    'Semantic_Background_bg_info': 'Basic_Info_info_600',
    'Semantic_Background_bg_black_3': 'Basic_Neutral_Neutral_600',
    'Semantic_Background_bg_black_4': 'Basic_Neutral_Neutral_500',
    'Semantic_Background_bg_success_light': 'Basic_Success_success_50',
    'Semantic_Background_bg_info_light': 'Basic_Info_info_50',
    'Semantic_Background_bg_primary_light': 'Basic_Primary_primary_50',
    'Semantic_Background_bg_danger_light': 'Basic_Danger_danger_50',
    'Semantic_Background_bg_warning_light': 'Basic_Warning_warning_50',
    'Semantic_Background_bg_secondary': 'Basic_Secondary_secondary_600',
    'Semantic_Background_bg_soft': 'Basic_Neutral_Neutral_25',
    'Semantic_Background_bg_supersoft': '#f6f6f6',
    'Semantic_Background_bg_disable': 'Basic_Neutral_Neutral_350',
    ...ThemeBaseColors.Neon_2_0,
  },
};

export default Colors;

export type ColorsType = {
  [key in ColorKeys]: string;
};
